export const ImagesAndIcons = {
    branches: require('../assets/icons/branches.png'),
    cardProfile: require('../assets/icons/cardProfile.png'),
    complaintsLog: require('../assets/icons/complaintsLog.png'),
    complaint: require('../assets/icons/complaint.png'),
    cardRequest: require('../assets/icons/cardRequest.png'),
    searchsm: require('../assets/icons/searchsm.png'),
    calender: require('../assets/icons/calendar.png'),
    filterlines: require('../assets/icons/filterlines.png'),
    cards: require('../assets/icons/cards.png'),
    cardScheme: require('../assets/icons/cardScheme.png'),
    roles: require('../assets/icons/roles.png'),
    dashboard: require('../assets/icons/dashboard.png'),
    reissuePin: require('../assets/icons/reissuePin.png'),
    stock: require('../assets/icons/stock.png'),
    unblockCard: require('../assets/icons/unblockCard.png'),
    users: require('../assets/icons/users.png'),
    cardFinaLogo: require('../assets/icons/cardFinaLogo.png'),
    logoutTwo: require('../assets/icons/logoutTwo.png'),
    complaintResolved: require('../assets/icons/complaintsResolved.png'),
    LAPOLOGO: require('../assets/icons/LAPOLOGO.png'),
    bellIcon: require('../assets/icons/bellIcon.png'),
    Dropdown: require('../assets/icons/Dropdown.png'),
}