export const ImagesAndIcons = {
    branches: require('../assets/icons/branches.png'),
    cardProfile: require('../assets/icons/cardProfile.png'),
    complaintsLog: require('../assets/icons/complaintsLog.png'),
    complaint: require('../assets/icons/complaint.png'),
    cardRequest: require('../assets/icons/cardRequest.png'),
    searchsm: require('../assets/icons/searchsm.png'),
    calender: require('../assets/icons/calendar.png'),
    filterlines: require('../assets/icons/filterlines.png'),
    activeCard: require('../assets/icons/activeCard.png'),
    alertCircle: require('../assets/icons/alertCircle.png'),
    arrowUp: require('../assets/icons/arrowUp.png'),
    maximize: require('../assets/icons/maximize.png'),
    homeIcn : require('../assets/icons/homeIcn.png'),
    issueInstant: require('../assets/icons/issueInstant.png'),
    issuePersonalized: require('../assets/icons/issuePersonalized.png'),
    manageIcon: require('../assets/icons/manageIcon.png'),
    pendingRequest: require('../assets/icons/pendingRequest.png'),
    personalized: require('../assets/icons/personalized.png'),
    revenue: require('../assets/icons/revenue.png'),
    reviewIcon: require('../assets/icons/reviewIcons.png'),
    rightArrow: require('../assets/icons/rightArrow.png'),
    cards: require('../assets/icons/cards.png'),
    cardScheme: require('../assets/icons/cardScheme.png'),
    roles: require('../assets/icons/roles.png'),
    dashboard: require('../assets/icons/dashboard.png'),
    reissuePin: require('../assets/icons/reissuePin.png'),
    stock: require('../assets/icons/stock.png'),
    unblockCard: require('../assets/icons/unblockCard.png'),
    users: require('../assets/icons/users.png'),
    cardFinaLogo: require('../assets/icons/cardFinaLogo.png'),
    logoutTwo: require('../assets/icons/logoutTwo.png'),
    complaintResolved: require('../assets/icons/complaintsResolved.png'),
    LAPOLOGO: require('../assets/icons/LAPOLOGO.png'),
    bellIcon: require('../assets/icons/bellIcon.png'),
    Dropdown: require('../assets/icons/Dropdown.png'),
}